### ISSUE TITLE
Numpy attribute error 

### ISSUE THREAD

**Issue by Bovornpratch** [legolason/PyQSOFit#42]
Hi,

 I am looking to fit some spectra of AGN using pyQSOfit and ran in to an issue related to numpy attributes when testing the with the example. What is the working numpy version for pyQSOfit  (also for other packages would be nice to know too.) 

My package setup includes
numpy 1.20.0
scipy 1.6.0
astropy 5.1
PyAstronomy 0.18.0
Sfdmap  0.1.1
kapteyn 3.0
python 3.8

I know that the running version is python 3.6 and I will check with that in a bit. I'm opening the ticket  since the current issue seem to be more related to numpy. 

Cheers,

Klod

> AttributeError                            Traceback (most recent call last)
<ipython-input-13-85608e4d419e> in <module>
      4 start = timeit.default_timer()
      5 # do the fitting
----> 6 q.Fit(name = None,nsmooth = 1, and_or_mask = False, deredden = True, reject_badpix = False, wave_range = None,\
      7       wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20, \
      8       Fe_uv_op = True, Fe_flux_range=np.array([4435,4685]), poly = True, BC = False, rej_abs = False, \
~/ext_disk/disk_1/Dropbox/studies/Research/Data_reduction/WERGS/data_anal/specfit/WERGS_2021/HSC_42045337531063074/PyQSOFit-master/example/../pyqsofit/PyQSOFit.py in Fit(self, name, nsmooth, and_or_mask, reject_badpix, deredden, wave_range, wave_mask, decomposition_host, BC03, Mi, npca_gal, npca_qso, Fe_uv_op, Fe_flux_range, poly, BC, rej_abs, initial_guess, MC, n_trails, linefit, tie_lambda, tie_width, tie_flux_1, tie_flux_2, save_result, plot_fig, save_fig, plot_line_name, plot_legend, dustmap_path, save_fig_path, save_fits_path, save_fits_name)
    405         if linefit == True:
    406 
--> 407             self._DoLineFit(self.wave, self.line_flux, self.err, self.conti_fit)
    408         else:
    409             self.ncomp = 0
~/ext_disk/disk_1/Dropbox/studies/Research/Data_reduction/WERGS/data_anal/specfit/WERGS_2021/HSC_42045337531063074/PyQSOFit-master/example/../pyqsofit/PyQSOFit.py in _DoLineFit(self, wave, line_flux, err, f)
    910             for ii in range(ncomp):
    911                 compcenter = allcompcenter[ii]
--> 912                 ind_line = np.where(linelist['compname'] == uniq_linecomp_sort[ii], True, False)  # get line index
    913                 nline_fit = np.sum(ind_line)  # n line in one complex
    914                 linelist_fit = linelist[ind_line]
~/.local/lib/python3.8/site-packages/pyfits/py3compat.py in __getitem__(self, obj)
    101                 if isinstance(val, numpy.character):
    102                     temp = val.rstrip()
--> 103                     if numpy.char._len(temp) == 0:
    104                         val = ''
    105                     else:
**AttributeError: module 'numpy.core.defchararray' has no attribute '_len'**

**Comment by burke86** [comment]
Thanks for reporting the issue @Bovornpratch. Perhaps @legolason can comment about what versions he has tested v1.1 of the code with.
We are working on a significant code update to v1.2 at PR #41. That version should work better with these more modern versions. You are welcome to try it out now but it's not ready for release yet.

**Comment by Bovornpratch** [comment]
@burke86  thanks for a reply. That is good to hear. A quick update is that it seem I got the example to work with the following set up after some small changes to the path of data files and FeII templates.  

python 3.8.10
numpy  1.19.0
scipy 1.9.0
sfdmap 0.1.1
astropy 5.1
PyAstronomy 0.18.0
Kapteyn 3.0 

I mainly use pip to grab these packages and was tested in a virtual enviroment+jupyter.  One note is that Kapteyn was build using `pip install https://www.astro.rug.nl/software/kapteyn/kapteyn-3.0.tar.gz` from the user guild 
https://www.astro.rug.nl/software/kapteyn/intro.html#installing

I will test this a bit more with what I'm doing for now but also let me know that official prerequisites. Also looking forward to v1.2!

**Comment by legolason** [comment]
Good to hear you have solved this problem!
